spring.application.name=TestArena
server.port=9091

# Gemini settings
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
gemini.api.key=YOUR_OWN_KEY

# Google Custom Search
google.cse.url=https://www.googleapis.com/customsearch/v1
google.api.key=YOUR_GCSE_KEY
google.cse.cx=YOUR_CX

# Other tuning
gemini.temperature=0.0
gemini.maxOutputTokens=700

#DB
spring.datasource.url=jdbc:mysql://localhost:3306/testarena?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect (Auto for Spring Boot 3.x)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect